# Generated by Django 5.1.4 on 2024-12-17 01:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_closed_auction_winner_alter_auction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to='auctions.auction'),
        ),
    ]
